# docker-compose-dev.yml (for local development)

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

    ports:
      - "12181:2181" # Expose Zookeeper on host port 12181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_LISTENERS defines what interfaces Kafka binds to INSIDE the container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      # KAFKA_ADVERTISED_LISTENERS defines how clients connect to Kafka
      # PLAINTEXT is for internal docker network communication (service name `kafka`)
      # PLAINTEXT_HOST is for external communication (from your host machine via `localhost`)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      #  THIS IS THE CRUCIAL MISSING PIECE VVVVV
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #  THIS IS GOOD PRACTICE FOR THE BROKER TO KNOW WHICH LISTENER TO USE FOR INTERNAL COMMUNICATION
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Optional: If you encounter "Controller moved to another broker" issues with single node,
      # you might need this, but usually KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 is enough for single node.
      # KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092" # Exposes the PLAINTEXT_HOST listener (9092 internally) to port 9092 on host
    restart: on-failure

  mariadb:
    image: mariadb:11.0
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: default_root_password_dev
       MYSQL_DATABASE: billing_system_dev
       MYSQL_USER: billing_user_dev
       MYSQL_PASSWORD: billing_password_dev


  redis:
    image: redis:7.2-alpine
    restart: on-failure
    ports:
      - "6379:6379" # Expose Redis on host port 16379
    volumes:
      - redis_dev_data:/data # Persist Redis data for dev


volumes:
  kafka_dev_data:
  redis_dev_data:
  zookeeper_data:
  zookeeper_log: