# version: '3.8' # This line is optional with modern Docker Compose

services:
  mariadb:
    image: mariadb:11.0
    healthcheck:
    
      test: ["CMD-SHELL", "mysqlshow -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --status > /tmp/healthcheck_status.log 2>&1 || exit 1"]
      #test: ["CMD", "mysql", "-h", "127.0.0.1", "-u", "root", "-pe2e_very_secret_root_password", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 12 # Increased from your original 5 for more resilience
      start_period: 60s # Increased from your original 30s for more init time
    restart: on-failure
    # Default environment variables for MariaDB can be added here if desired for non-E2E local 'docker-compose up'
    # For E2E, these will be overridden by docker-compose.e2e.yml
    # environment:
    #   MYSQL_ROOT_PASSWORD: default_root_password_dev
    #   MYSQL_DATABASE: billing_system_dev
    #   MYSQL_USER: billing_user_dev
    #   MYSQL_PASSWORD: billing_password_dev

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    restart: on-failure

  redis:
    image: redis:7.2-alpine
    restart: on-failure

  policy-service:
    build:
      context: .
      dockerfile: policy-service/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      mariadb:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    restart: on-failure
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      # DB_NAME, DB_USER, DB_PASSWORD will come from override files or app defaults

  billing-service:
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      mariadb:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    restart: on-failure
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      mariadb:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
      payment-gateway-mock:
        condition: service_started
    restart: on-failure
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PAYMENT_GATEWAY_MOCK_URL: http://payment-gateway-mock:8090/api/gateway
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8084:8080"
    command: /bin/sh -c "java -jar app.jar > /app/startup.out 2>&1 || (echo 'NOTIFICATION SERVICE CRASHED - STDOUT:' && cat /app/startup.out && echo 'NOTIFICATION SERVICE CRASHED - STDERR (if different from STDOUT):' && echo 'SLEEPING NOW' && sleep 300)"
    depends_on:
      mariadb:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    restart: on-failure
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true

  payment-gateway-mock:
    build:
      context: .
      dockerfile: payment-gateway-mock/Dockerfile
    ports:
      - "8090:8080"
    restart: on-failure

volumes:
  zookeeper_data:
  zookeeper_log: